# Generated by Django 3.0.7 on 2020-06-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='previous_password',
            field=models.CharField(default=models.CharField(max_length=128, verbose_name='password'), max_length=128, verbose_name='previous password'),
        ),
    ]
