# Generated by Django 3.0.6 on 2020-06-14 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0002_auto_20200614_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login2',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login2'),
        ),
    ]
