# Generated by Django 3.0.7 on 2020-06-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0002_auto_20200619_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='previous_password',
            field=models.CharField(default='', max_length=128, verbose_name='previous password'),
        ),
    ]
