# Generated by Django 3.0.6 on 2020-06-14 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0003_auto_20200614_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='last login'),
        ),
    ]
